manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tominabox1
      url-base: https://github.com/tominabox1/
    - name: nicell
      url-base: https://github.com/Nicell/
    - name: okke
      url-base: https://github.com/okke-formsma
  projects:
    - name: zmk
      remote: tominabox1
      revision: chormbo2.4
      import: app/west.yml
  self:
    path: config
